# My personal "notes" for tensors in pytorch

In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

# Check PyTorch version
torch.__version__

'2.6.0+cu124'

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name(torch.cuda.current_device())

'NVIDIA A100-SXM4-40GB'

Tensor?
A tensor is something like "multidimensional array"
Pytorch Tensor: A specialized data structure that are very similar to arrays and matrices

Scalar
 a single number/zero dimension tensor

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Vector
A tensor with a single dimension, that contains many numbers
essentially a number with direction (e.g. wind speed with direction) but can also have many other numbers

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# Check the number of dimensions of vector
vector.ndim

1

In [9]:


# Check shape of vector
vector.shape


torch.Size([2])

Counting dimensions?
Just count the square brackets on one side

Matrix
a 2-dimensional array of numbers

In [10]:
# Matrix, here its in 2 dimensions
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Check number of dimensions
MATRIX.ndim

2

In [12]:
# See! it has 2 dimensions and is 2 by 2 matrix
MATRIX.shape

torch.Size([2, 2])

Tensor
an n-dimensional array of numbers
can be noted as mxn aka rowxcol

![alt text](00-pytorch-different-tensor-dimensions.png)

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Check number of dimensions for TENSOR or use the square bracket trick!
TENSOR.ndim

3

In [15]:
# Check shape of TENSOR
TENSOR.shape
# what is this?
# it means that the tensor has 1 row, inside there are 3 more and finally, it contains 3 numbers

torch.Size([1, 3, 3])

In [16]:
# clearer definition
TENSOR = torch.tensor([[[1, 2, 3,4],
                        [3, 6, 9,11],
                        [2, 4, 5,44]]])
# will output 1,3,4
TENSOR.shape 

torch.Size([1, 3, 4])

Torch Randoms
Useful to create random data for datasets or training like..

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...```

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2768, 0.7390, 0.5392, 0.5413],
         [0.4806, 0.9347, 0.7707, 0.5697],
         [0.9119, 0.8574, 0.3353, 0.1811]]),
 torch.float32)

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Torch arrange
if you want a range of values

```torch.arange(start, end, step)```

In [21]:
# Use torch.arange(), torch.range() is deprecated 
# both are deprecated bruh, use random instead
import random
zero_to_ten = random.randrange(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Datatypes
- torch.cuda
- torch.float64/torch.double
- torch.float32 ->default
- torch.float16/torch.half

### Note
Pytorch prefers same device calculations and datatypes

In [22]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [28]:
# Example debug of a tensor
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9930, 0.2452, 0.1329, 0.8212],
        [0.6584, 0.9371, 0.0367, 0.4999],
        [0.9432, 0.5472, 0.7520, 0.1562]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations

In [29]:
# Create a tensor of values and add a number to it
# Tensors don't change unless reassigned
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply it by 10
tensor * 10
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [33]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

Matrix multiplication - torch.matmul()

Main rules
    The inner dimensions must match:

    (3, 2) @ (3, 2) won't work
    (2, 3) @ (3, 2) will work
    (3, 2) @ (2, 3) will work

    The resulting matrix has the shape of the outer dimensions:

    (2, 3) @ (3, 2) -> (2, 2)
    (3, 2) @ (2, 3) -> (3, 3)

This is useful for LoRA

### Wait!
Remember, this is matrix multiplication row with col the other one is called element wise multipication element with element

In [49]:
tensor1=torch.rand(3, 4)
tensor2=torch.rand(4, 3)
tensor3=torch.rand(3, 3)
# Matmul
print(torch.matmul(tensor1, tensor2))
print(torch.mm(tensor1, tensor2))
matmulres=tensor1@tensor2
# Element Wise
print(matmulres*tensor3)


tensor([[0.6443, 0.4402, 0.1085],
        [2.0703, 1.7916, 0.7929],
        [1.3563, 1.1399, 0.6048]])
tensor([[0.6443, 0.4402, 0.1085],
        [2.0703, 1.7916, 0.7929],
        [1.3563, 1.1399, 0.6048]])
tensor([[0.3446, 0.2192, 0.0065],
        [0.7785, 0.4217, 0.4505],
        [0.9005, 0.1538, 0.5836]])


Transpose

    torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
    tensor.T - where tensor is the desired tensor to transpose.


In [48]:
# you can also do transpose if you wanna flip dims and whatnot
tensor1.T@tensor2.T

tensor([[0.2992, 0.7457, 0.0385, 0.2284],
        [0.6223, 1.2526, 0.2129, 0.4965],
        [0.9099, 1.4866, 0.4438, 0.7824],
        [1.0546, 1.7269, 0.5123, 0.9073]])

In [55]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
# transpose cause it doesnt amtch
x = tensor1.T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([4, 3])

Output:
tensor([[ 0.1159,  0.1307,  0.2328,  0.3807, -0.0100,  0.7983],
        [ 0.3279,  0.3413,  0.2538,  0.2990,  0.2142,  0.8390],
        [ 0.0407,  0.2010,  0.1515,  0.2425,  0.0122,  0.6974],
        [-0.0379,  0.1382,  0.2057,  0.2922, -0.0339,  0.7012]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([4, 6])


Aggregation & Positional arguments

In [57]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [58]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [59]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [68]:
# change datatype
#torch.Tensor.type(dtype=None)
tensor32= torch.arange(10., 100., 10.)
print(tensor32.dtype)
tensor8=tensor32.type(torch.int8)
print(tensor8.dtype)

torch.float32
torch.int8


In [69]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [70]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [72]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

changing the view of a tensor with torch.view() really only creates a new view of the same tensor.it will change the original tensor too

In [74]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [73]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [75]:
# Torch squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [81]:
# Torch unsqueeze
# add a dimension value at an index
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


In [83]:
# Rearanging order of axes
# Create tensor with specific shape
x_original = torch.rand(size=(220, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([220, 224, 3])
New shape: torch.Size([3, 220, 224])


### Data Selections

In [84]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [86]:
# tensor([[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]])
# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 0])
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[1, 4, 7]])
tensor([5])
tensor([5])
tensor([1, 2, 3])


Pytorch & numpy interchangable
- torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
- torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [87]:

# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note:
Use torch.manual_seed(seed=12) 

In [110]:
torch.manual_seed(seed=12) 
random_tensor_C = torch.rand(3, 4)
# you only eed to add this before your statement!
torch.manual_seed(seed=12) 
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)

tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871],
        [0.4086, 0.1272, 0.6373, 0.2421],
        [0.7312, 0.7224, 0.1992, 0.6948]])


In [112]:
!nvidia-smi

Thu Feb 20 08:22:42 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          On  | 00000000:47:00.0 Off |                    0 |
| N/A   42C    P0              53W / 275W |      3MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--